### PR TITLE
More descriptive naming in the code: rename PSerial1 to SerialWiFi

### PR DESCRIPTION
**Pull request by kbahey**
It was confusing for me to know what PSerial and PSerial1 are. So renamed 1 to WiFi throughout. Still don't know what Serial4 is.

### CODE REVIEW

**Comment by hjd1964** [comment]
PSerial is the first serial channel (Serial usually, normally USB)
PSerial1 is the second serial channel (Serial1 usually, BT or Wifi, or Ethernet but not always)
PSerial4 is the third serial channel (Serial4 usually, BT or Wifi or Ethernet but not always)
PSerialST4 is the ST4 serial channel for the hand controller.

It would improve consistency if PSerial4 were renamed to PSerial2 I suppose.  Serial4 on the Teensy3.5 or 3.6 happened to be at conveniently available pins so that's what I did.

**Comment by kbahey** [comment]
What is the 3rd serial channel for? Seems identical to Serial1.

**Comment by hjd1964** [comment]
It's a spare serial channel.  Some want BT and Wifi, or BT and Ethernet.  Or RS232.  Or if we add real GPS support they are TTL serial usually.

**Comment by kbahey** [comment]
Great.

So let us improve the naming: decouple the name from the number.

So:
Serial -> PSerial
PSerialA to PSerialC -> whatever HAL defines
That way, different platforms can have different port numbers

Same for HAL_SERIALx_ENABLED -> HAL_SERIAL_B_ENABLED

I can work on a pull request for this.

**Comment by hjd1964** [comment]
Really the name is already decoupled from the actual serial port number... that's the point of #defining them.  This really amounts to nothing more than scratching an itch, but feel free.  Lets go one step further though and drop the "P" prefix.

SerialA
SerialB
SerialC
SerialST4

**Comment by kbahey** [comment]
It is more about avoiding confusion. STM32, and TivaC have PSerial1 defined as Serial2 and Serial7, and that may confused people building boards, or reading/modifying code. 

See the other pull request.

**Pull request closed without merging**
