### PR TITLE
Build a new user interface for SmartWebController

### PR DESCRIPTION
**Pull request by jgill88**
# Problem 

The existing SmartWebController was difficult for me to use on mobile and I wanted a standalone solution that didn't require anything except for the WiFi server and a browser.

# My solution

Designed and implemented a single page application user interface using VueJS, Tailwindcss, and a few other ancillary libraries.

The front-end is written in Typescript, with manually created types that match the API data returned by the WiFi server. This allows for rich typechecking while building the UI, as well as understanding the flow & types of data through the application.

I recommend VSCode for working with Vue & Typescript- in my experience this is the best development experience.

# New features

## Responsiveness

The whole app is built mobile-first. It's very responsive on mobile and looks great on desktop. Big buttons, etc.

## Library 

There is now and embedded & searchable library of bright stars - taken & parsed from the SmartHandController codebase. 

You can fuzzy search these stars and GoTo them. Additionally, there's an area to GoTo arbitrary coordinates - and when you do, it saves the arbitrary GoTo to the catalogs automatically for future use (and includes them in the library list at the top).

As it turns out, the library I scraped from SHC is only a small part of the final build - I think we could include several more pre-made libraries from the SHC - just depending on how big we want the bundle to be.

## Loading states & disabled states

There are many cases in the existing UI where buttons are active but don't do anything yet. In general, this new UI disables buttons when the button isn't going to do anything.

Also, when a button/toggle is performing an asynchronous action that takes time, the UI element has a loading spinner to indicate that it's doing something - if the UI doesn't detect an expected status change within a certain period of time, the UI attempts to notify the user what's going on. In some cases, we can provide helpful error messages so the user isn't wondering what's happening. I plan to flesh out this error handling out a lot further.

## Date/time sync

As the date/time sync is really important, a warning icon is shown in the menu if the date/time appears to be out of sync. You can follow the warning icons to the area that lets you sync up the time. 

## Big ole e-stop

The navbar has a big e-stop icon in the upper right everywhere - if you need to kill the motion for some reason, it's ready to use.

## Terminal

A simple REPL terminal has been added for advanced uses. 

# UI preview

The README in the single page app folder [here](https://github.com/jgill88/OnStep/blob/new-ui/addons/WiFi/onstep-ui/README.md) includes some screenshots to preview the UI, as well as instructions for building the app.

# Build process 

The app is built using Vite - once Vite finishes bundling the application, a few small custom plugins transform the output into a single `output.h` file - this file contains the gzipped bytes of the application. This file gets (currently manually) copied over to `../NewUI.h`. From there, an endpoint in the WiFi server simply serves these gzipped bytes directly to the browser -- this current build comes in at ~102kB gzipped. This might be too large for some hardware out there, but I'm honestly not sure what kind of space limits we have. If this UI were to be completed and accepted, the existing embedded HTML could be removed which would save on space, too. I doubt it's 100k, but it's at least some.

# Testing this out 

In this PR, the NewUI.h file is already built -- so if you'd like to try out this UI, you don't need to do anything except check this branch out and download it to your ESP. I'm using an ESP8255 and do not have other hardware to test with unfortunately.

The existing UI is preserved and is located under `/old`.

# API

As this interface is primarily API driven, a few new AJAX endpoints were added to the WiFi server that pull together various parts of existing code so that the user interface can easily consume the OnStep status. Most all mutation-related actions use the existing handlers with the exception of addition of an arbitrary command endpoint.

There were a few other existing API endpoints that were sufficient out of the box.

# Notes:

I recognize that this is a radical change to the existing user interface - and if I were the maintainer of OnStep, I'm not sure I'd be thrilled about a massive change out of the blue like this by someone else -- that said, I'm excited by the OnStep project and would like to at least offer this back to the community should it be of interest.

I wouldn't be offended if this was not something you're willing to take on. I plan to continue developing this and enhancing the feature set as I use it regardless, so no hurt feelings here. 

# There's a few wins here:

1) You can develop & run this UI on your computer - including things like hot module reloading, etc for fast development - as opposed to having to download and run C code as the interface gets worked on -- so long as you don't have to add/edit endpoints on the ESP, all development can be done against a running ESP on your computer -- until you're happy with the UI, then `yarn build` -> copy file -> program ESP.
2) Using modern front end frameworks, we can get really rich & reactive user interfaces that are simple to build. 
3) Things like loading states, disabled states, etc, are all imho easier to implement on the client side as opposed to server side - we just need to know the current state of OnStep, and then build the UI business logic into the client-side code. 
4) Tailwindcss (or any other modern css framework) makes responsiveness & layouts a cinch. 

# Status

There are a couple areas of this UI that are not complete yet; however it's pretty enjoyable & usable in its current state. Over the coming couple weeks, I plan to wrap up the incomplete areas.

Thank you for any time you spend considering or checking out this project!
- Josh

### CODE REVIEW

**Comment by hjd1964** [comment]
That sounds nice.

One problem is that this is a release, so no new features just the occasional minor bug patch is allowed.

Further, the WiFi Addon within is obsolete and has been replaced with the [SmartWebServer](https://github.com/hjd1964/SmartWebServer) or SWS.

The SWS combines the Ethernet and WiFi Addons and extends them with features to support [OnStepX](https://github.com/hjd1964/OnStepX) but is also compatible with OnStep release-3.16 and later.

Additionally, OnStepX has a website plugin where there is much shared code with the SWS.

The UI and code under the hood has changed **a lot** since this version.

**Comment by hjd1964** [comment]
Oh yea, it's the main branch you would want to look at if adding these features:
https://github.com/hjd1964/SmartWebServer/tree/main

All of my current software is developed in Visual Studio Code (with the Arduino plugin) but compiled in the Arduino IDE.

**Comment by hjd1964** [comment]
Here's the website plugin:
https://github.com/hjd1964/OnStepX-Plugins

**Comment by jgill88** [comment]
Thanks Howard!

I'd be happy to take a look at SWS/the Website plugin and move things over -- 

If I did so, do you think that this UI is headed in a direction that'd be something you would merge (after complete and testing?)

Josh

**Comment by jgill88** [comment]
The SWS has definitely changed a lot (seems a lot easier to follow!); but honestly, this would port over without much effort.

**Comment by hjd1964** [comment]
I tried your website plugin, all I get is "There was an issue connecting to your mount."
Running on an WeMos D1 Mini using libraries 2.4.2

OnStep side is release-4.24 on a MaxPCB2, fairly boring setup just the basics.

Comes up fine w/ the latest SWS.

We should move this conversation to the developer group, much more comfortable there:
https://onstep.groups.io/g/developer/topics

**Pull request closed without merging**
