### PR TITLE
Temperature of secondary mirror for the dew-heater.

### PR DESCRIPTION
**Pull request by plop3**
Hello,

I made a small modification for the dew-heater.
On my Newtonian telescope, I use the DS1820 attached to the secondary mirror and a set of resistors to heat the mirror.
I maintain the temperature 2 ° above the dew point.
Thus, I do not heat too much to avoid turbulence.

The DS1820 gives the temperature of the secondary mirror.
The BME280 provides the dew point temperature.
I use the Mosfet output (Ramps card) for heat the mirror.

I added in Config.h: #define MIRROR_TEMPERATURE DS1820 // OFF
And #define OneWirePin 49 (Which is not present for the Ramps card).

I also reduced the acquisition time of the temperature values (~ 30s) if that is not a problem.

I send you the changes if you want to integrate it with OnStep.

### CODE REVIEW

**Comment by hjd1964** [comment]
I like the way it's implemented, rather nice.

One thing I'd like to see is provision for multiple DS18B20's on a single bus.  Perhaps by index like this:

#define TELESCOPE_TEMPERATURE OFF  // ON (single device) or n = device index
#define DEW_HEATER1_TEMPERATURE OFF // ON (single device) or n = device index
#define DEW_HEATER2_TEMPERATURE OFF // ON (single device) or n = device index
#define DEW_HEATER3_TEMPERATURE OFF // ON (single device) or n = device index

Then use getDeviceCount() to figure out how many we have and getTempCByIndex()...
Validate so that a single device enabled with ON is ok but if > one enabled they all have to specify the index.

See:
https://lastminuteengineers.com/multiple-ds18b20-arduino-tutorial/

**Comment by hjd1964** [comment]
If a given dew heater channel doesn't have a DEW_HEATERn_TEMPERATURE it falls back to the telescope temperature and current control scheme.

If you don't want to take things this far I will probably merge anyway then take it from there.  If you do want to do the work great.

Much appreciated either way.

**Comment by hjd1964** [comment]
BTW I do plan to add control of these dew heaters from the Android App, SHC, website.  And w/memory of the settings in NV.

**Comment by plop3** [comment]
Thank you
I will try to work on the possibility of using several DS1820 (several for dew-heater and one for the focuser).

I found on: http://henrysbench.capnfatz.com/henrys-bench/arduino-temperature-measurements/ds18b20-arduino-user-manual-introduction-and-contents/ds18b20-arduino-users-manual-part- 3-reading-a-single-temperature /

DS1820 acquisition times:

Resolution Time Increment
9 bit 0.5 degrees C 93.75 mSec
10 bit 0.25 degrees C 187.5 mSec
11 bit 0.125 degrees C 375 mSec
12 bit 0.0625 degrees C 750 mSec

. Isn't that going to be a problem?
If yes, it is possible to read the values of the DS1820 in two stages:
Phase 1:
if (ds.reset ()) {
ds.write (0xcc);
ds.write (0x44,1);
}

Phase 2:

byte data[12];
if (ds.reset ()) {
ds.write (0xcc);
ds.write (0xBE);
int i;
for (i = 0; i <2; i ++) {
data [i] = ds.read ();
}
int16_t raw = (data [1] << 8) | data [0];
Tmirror = (float) raw / 16.0;
}

**Comment by hjd1964** [comment]
A few issues but overall looks good so I merged.

I then changed a few things:
1. Allowed backwards compatibility with Config.h files without DEW_HEATER.... defines
2. Unified the parameters set so same applies to telescope temperature as dew heater.
3. Weather.ino: Defines were simplified. Staggered execution so dew heater/telescope query for temperature (etc.) happens one at a time.

**Comment by hjd1964** [comment]
Thinking for DEW_HEATER setup...
#define **DEW_HEATER1 OFF** // OFF, ON (for default pin-map defined location) or n for any pin you like.

Get rid of **DEW_HEATER1_PIN**

etc.

**Comment by hjd1964** [comment]
Please review my changes to see if they look right to you.  Between the two of us maybe this has a decent shot at actually working ;)

**Comment by hjd1964** [comment]
I updated again to finish the preliminary design of this off.   I made some changes to how control is done going back to the proportional control (vs your basic threshold on/off design) but with a very narrow range so it should accomplish roughly the same thing.

The only OnStep related feature I really want to see added at this point is the ability to set/get (and store in NV) the proportional control low/high values for each heater.

Once this is confirmed to work I/we can add control the the website, SHC, Android App.

**Comment by plop3** [comment]
Hello,

Very good new, thanks.
I'm having some tests done this weekend to see if everything is ok.
If think, the next step is to add specfic commands to retrieve informations of heaters.
For example:
I think, :H is not currently used.
:Htx# Return the current temperature of DS1820 (x is the heater number)
:Hsx# Return the heater state (On/Off, level ?)
I will try to add these two commands this week.

26 février 2020 19:13 "Howard Dutton" <notifications@github.com (mailto:notifications@github.com?to=%22Howard%20Dutton%22%20<notifications@github.com>)> a écrit:
	I updated again to finish the preliminary design of this off. I made some changes to how control is done going back to the proportional control (vs your basic threshold on/off design) but with a very narrow range so it should accomplish roughly the same thing. 

	The only OnStep related feature I really want to see added at this point is the ability to set/get (and store in NV) the proportional control low/high values for each heater. 

	Once this is confirmed to work I/we can add control the the website, SHC, Android App.

**Comment by hjd1964** [comment]
> I think, :H is not currently used.
> :Htx# Return the current temperature of DS1820 (x is the heater number)
> :Hsx# Return the heater state (On/Off, level ?)
> I will try to add these two commands this week.

I also have some custom LX200 commands scattered here and there but more recently all custom OnStep LX200 commands go into :SXcc,value# and :GXcc#

:SXL1,-3# // set heater 1 **L**ow Delta C (at or below -3C is 100% power)
:GXL1# // returns -3#
:SXH1,15# // set heater 1 **H**igh Delta C (at or above 15C is 0% power)
:GXH1# // returns 15#
:GXh1# // get **h**eater 1 temperature

**Comment by hjd1964** [comment]
Probably these too.,,
:SXh1,0# // turn off heater 1
:SXh1,1# // turn on heater 1

**Pull request merged**
