### PR TITLE
Set time in 24hrs fromat & Quit menu after Parking/Unparking

### PR DESCRIPTION
**Pull request by peterdulowsky**

### CODE REVIEW

**Comment by hjd1964** [comment]
In my opinion setting time in 24 hour format is an extra hassle for users (myself included) so I'm going to pass on this one also.  If you'd like to #ifdef it I'll merge that way though.  I'll add in the parking/menu related changes manually here.  I'm also merging my changes, a work in progress, so be sure to pull those in before reworking that time code if you decide to.

**Comment by peterdulowsky** [comment]
Well, we don't use 12 hours format over here. I assumed it would be better to change this to 24 hrs to be consistent with time shown in the website and the time screen in SHC.

**Comment by hjd1964** [comment]
Well, we do over here and my opinion is that this rules over consistency in this case.

As I said #ifdef it and allow the option of either but I'm not making it 24hr only.

**Comment by peterdulowsky** [comment]
Fair enough, let's leave it as it is now.

**Comment by hjd1964** [comment]
Don't get me wrong though, my feeling is that it's a good option to have.  Perhaps even a menu item to let the user decide at run-time.

**Comment by hjd1964** [comment]
I've coded this 24hr mode and added an option to Config.h to select either.  
Will test tonight then release.

**Comment by peterdulowsky** [comment]
Thank you

**Pull request closed without merging**
